import { BenchCommand, BenchCommandCategory } from '../types';

/**
 * Complete registry of every bench and frappe CLI command.
 *
 * Source: bench/commands/*.py + frappe/commands/*.py
 * Captures every click command defined in the Frappe framework
 * and the bench CLI tool.
 *
 * Each command has:
 *   - template: string with {placeholder} tokens → resolved before execution
 *   - destructive: flag → requires explicit confirmation
 *   - requiresSite: flag → UI prompts for --site value
 *
 * Dynamic options (--format, --verbose, etc.) are left out of the
 * template — they're intuitive and vary too much to enumerate.
 * Critical options ARE included (--yes, --force, --app, etc.).
 */

export const BENCH_COMMANDS: BenchCommand[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // INIT — Creating a new bench / Frappe environment
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'init',
    name: 'Init a new bench',
    description: 'Create a new Frappe bench directory',
    template: 'bench init {path}',
    category: 'init',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'drop',
    name: 'Drop a bench',
    description: 'Remove a bench directory',
    template: 'bench drop {path}',
    category: 'init',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'find-benches',
    name: 'Find benches',
    description: 'Find all bench directories in a location',
    template: 'bench find {location}',
    category: 'init',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'migrate-env',
    name: 'Migrate bench environment',
    description: 'Migrate the bench environment to a new Python version',
    template: 'bench migrate-env {python}',
    category: 'init',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'src',
    name: 'Show bench source',
    description: 'Show the bench source directory',
    template: 'bench src',
    category: 'init',
    destructive: false,
    requiresSite: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // APP — Installing, creating, removing apps
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'get-app',
    name: 'Get app from remote',
    description: 'Download an app from a git URL',
    template: 'bench get-app {git-url}',
    category: 'app',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'new-app',
    name: 'Create new app',
    description: 'Scaffold a new Frappe app from boilerplate',
    template: 'printf "{app-title}\\n{app-description}\\n{app-publisher}\\n{app-email}\\n{app-license}\\n{github-workflow}\\n{branch-name}\\n" | bench new-app {app-name}',
    category: 'app',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'remove-app',
    name: 'Remove app',
    description: 'Remove an app from the bench',
    template: 'bench remove-app {app-name}',
    category: 'app',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'exclude-app',
    name: 'Exclude app from updates',
    description: 'Exclude an app from bench update',
    template: 'bench exclude-app {app-name}',
    category: 'app',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'include-app',
    name: 'Include app in updates',
    description: 'Include an app back in bench update',
    template: 'bench include-app {app-name}',
    category: 'app',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'install-app',
    name: 'Install app on site',
    description: 'Install a Frappe app on a specific site',
    template: 'bench --site {site} install-app {app}',
    category: 'app',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'uninstall-app',
    name: 'Uninstall app from site',
    description: 'Remove an app from a site',
    template: 'bench --site {site} uninstall-app {app}',
    category: 'app',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'list-apps',
    name: 'List installed apps',
    description: 'Show all apps installed on a site',
    template: 'bench --site {site} list-apps',
    category: 'app',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'pip',
    name: 'Run pip',
    description: 'Run pip/uv inside the bench environment',
    template: 'bench pip {args}',
    category: 'app',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'validate-dependencies',
    name: 'Validate dependencies',
    description: 'Check all app dependencies are satisfied',
    template: 'bench validate-dependencies',
    category: 'app',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'remote-set-url',
    name: 'Set app remote URL',
    description: 'Change the remote URL of an app',
    template: 'bench remote-set-url {app} {git-url}',
    category: 'app',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'remote-reset-url',
    name: 'Reset app remote URL',
    description: 'Reset app remote URL to Frappe official',
    template: 'bench remote-reset-url {app}',
    category: 'app',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'remote-urls',
    name: 'Show app remote URLs',
    description: 'Show remote URLs of all apps',
    template: 'bench remote-urls',
    category: 'app',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'app-cache',
    name: 'Manage app cache',
    description: 'Clear or manage the app cache',
    template: 'bench app-cache',
    category: 'app',
    destructive: false,
    requiresSite: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SITE — Creating, managing, dropping sites
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'new-site',
    name: 'Create new site',
    description: 'Create a new Frappe site',
    template: 'bench new-site {site} --mariadb-root-password {mysql-root-password} --admin-password {admin-password}',
    category: 'site',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'use-site',
    name: 'Set default site',
    description: 'Set a site as the default for this bench',
    template: 'bench --site {site} use',
    category: 'site',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'list-sites',
    name: 'List all sites',
    description: 'Show all sites in this bench',
    template: 'bench --site {site} list-sites',
    category: 'site',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'migrate',
    name: 'Migrate site',
    description: 'Run all pending migrations for a site',
    template: 'bench --site {site} migrate',
    category: 'site',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'reinstall',
    name: 'Reinstall site',
    description: 'Drop and recreate the site database',
    template: 'bench --site {site} reinstall --yes',
    category: 'site',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'drop-site',
    name: 'Drop site permanently',
    description: 'Drop a site database and archive it',
    template: 'bench --site {site} drop-site --force',
    category: 'site',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'restore',
    name: 'Restore site from backup',
    description: 'Restore a site from a SQL dump file',
    template: 'bench --site {site} restore {sql-file-path}',
    category: 'site',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'partial-restore',
    name: 'Partial restore',
    description: 'Restore only specific tables from a SQL dump',
    template: 'bench --site {site} partial-restore {sql-file-path}',
    category: 'site',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'browse-site',
    name: 'Browse site in browser',
    description: 'Open a site in the default browser',
    template: 'bench --site {site} browse',
    category: 'site',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'add-to-hosts',
    name: 'Add site to hosts file',
    description: 'Add the site domain to /etc/hosts',
    template: 'bench --site {site} add-to-hosts',
    category: 'site',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'set-admin-password',
    name: 'Set admin password',
    description: 'Change the Administrator password for a site',
    template: 'bench --site {site} set-admin-password {password}',
    category: 'site',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'set-password',
    name: 'Set user password',
    description: 'Change password for a specific user',
    template: 'bench --site {site} set-password {user} {password}',
    category: 'site',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'add-system-manager',
    name: 'Add system manager',
    description: 'Add a user as System Manager',
    template: 'bench --site {site} add-system-manager {email}',
    category: 'site',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'add-user',
    name: 'Add user',
    description: 'Create a new user on the site',
    template: 'bench --site {site} add-user {email}',
    category: 'site',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'disable-user',
    name: 'Disable user',
    description: 'Disable a user account',
    template: 'bench --site {site} disable-user {email}',
    category: 'site',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'remove-from-installed-apps',
    name: 'Remove from installed apps',
    description: "Remove an app from the site's installed apps list",
    template: 'bench --site {site} remove-from-installed-apps {app}',
    category: 'site',
    destructive: true,
    requiresSite: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BACKUP — Backups and restore
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'backup',
    name: 'Backup site',
    description: 'Create a database and files backup',
    template: 'bench --site {site} backup',
    category: 'backup',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'backup-all-sites',
    name: 'Backup all sites',
    description: 'Backup every site in this bench',
    template: 'bench backup-all-sites',
    category: 'backup',
    destructive: false,
    requiresSite: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CONFIG — Site & bench configuration
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'show-config',
    name: 'Show site config',
    description: 'Display the site configuration',
    template: 'bench --site {site} show-config',
    category: 'config',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'set-config',
    name: 'Set site config',
    description: 'Set a value in site configuration',
    template: 'bench --site {site} set-config {key} {value}',
    category: 'config',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'set-common-config',
    name: 'Set common config',
    description: 'Set a value in the bench common config',
    template: 'bench config set-common-config {key} {value}',
    category: 'config',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'remove-common-config',
    name: 'Remove common config',
    description: 'Remove keys from bench common config',
    template: 'bench config remove-common-config {keys}',
    category: 'config',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'config-http-timeout',
    name: 'Set HTTP timeout',
    description: 'Set the HTTP timeout in common config',
    template: 'bench config http-timeout {seconds}',
    category: 'config',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'config-dns-multitenant',
    name: 'Toggle DNS multitenancy',
    description: 'Enable or disable DNS-based multitenancy',
    template: 'bench config dns-multitenant {state}',
    category: 'config',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'config-serve-default-site',
    name: 'Toggle default site serving',
    description: 'Configure nginx to serve the default site on port 80',
    template: 'bench config serve-default-site {state}',
    category: 'config',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'config-restart-supervisor',
    name: 'Toggle supervisor auto-restart',
    description: 'Enable/disable auto-restart of supervisor on update',
    template: 'bench config restart-supervisor-on-update {state}',
    category: 'config',
    destructive: false,
    requiresSite: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DATABASE — Database operations
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'console',
    name: 'Python console',
    description: 'Open a Frappe Python console for the site',
    template: 'bench --site {site} console',
    category: 'database',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'database',
    name: 'Database console',
    description: 'Open the database console (MariaDB/PostgreSQL/SQLite)',
    template: 'bench --site {site} database',
    category: 'database',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'mariadb',
    name: 'MariaDB console',
    description: 'Open the MariaDB console for the site',
    template: 'bench --site {site} mariadb',
    category: 'database',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'postgres',
    name: 'PostgreSQL console',
    description: 'Open the PostgreSQL console for the site',
    template: 'bench --site {site} postgres',
    category: 'database',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'sqlite',
    name: 'SQLite console',
    description: 'Open the SQLite console for the site',
    template: 'bench --site {site} sqlite',
    category: 'database',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'trim-database',
    name: 'Trim database',
    description: 'Remove orphaned tables from the database',
    template: 'bench --site {site} trim-database',
    category: 'database',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'trim-tables',
    name: 'Trim table columns',
    description: 'Drop unused columns from tables',
    template: 'bench --site {site} trim-tables',
    category: 'database',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'clear-log-table',
    name: 'Clear log tables',
    description: 'Prune old log entries from a log DocType',
    template: 'bench --site {site} clear-log-table --doctype {doctype} --days {days}',
    category: 'database',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'transform-database',
    name: 'Transform database',
    description: 'Transform database engine or row format',
    template: 'bench --site {site} transform-database',
    category: 'database',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'add-database-index',
    name: 'Add database index',
    description: 'Create an index on a DocType column',
    template: 'bench --site {site} add-database-index --doctype {doctype} --column {column}',
    category: 'database',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'describe-database-table',
    name: 'Describe database table',
    description: 'Show table structure for a DocType',
    template: 'bench --site {site} describe-database-table --doctype {doctype}',
    category: 'database',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'run-patch',
    name: 'Run a specific patch',
    description: 'Execute a specific migration patch',
    template: 'bench --site {site} run-patch {module}',
    category: 'database',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'bypass-patch',
    name: 'Bypass a patch',
    description: 'Permanently skip a specific patch',
    template: 'bench --site {site} bypass-patch {patch-name}',
    category: 'database',
    destructive: true,
    requiresSite: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DOCTYPE / SCHEMA — DocType operations
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'new-doctype',
    name: 'Create new DocType',
    description: 'Scaffold a new DocType in an app',
    template: 'bench new-doctype {name} --app {app}',
    category: 'doctype',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'reload-doctype',
    name: 'Reload DocType',
    description: 'Reload a DocType from its JSON file',
    template: 'bench --site {site} reload-doctype {doctype}',
    category: 'doctype',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'reset-perms',
    name: 'Reset permissions',
    description: 'Reset permissions for all DocTypes',
    template: 'bench --site {site} reset-perms',
    category: 'doctype',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'export-fixtures',
    name: 'Export fixtures',
    description: 'Export fixture records for an app',
    template: 'bench --site {site} export-fixtures --app {app}',
    category: 'doctype',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'data-import',
    name: 'Data import',
    description: 'Import documents from CSV/XLSX',
    template: 'bench --site {site} data-import --doctype {doctype} --file {file}',
    category: 'doctype',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'export-json',
    name: 'Export to JSON',
    description: 'Export a DocType or document to JSON',
    template: 'bench --site {site} export-json {doctype} {path}',
    category: 'doctype',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'export-csv',
    name: 'Export to CSV',
    description: 'Export a data import template with data for DocType',
    template: 'bench --site {site} export-csv {doctype} {path}',
    category: 'doctype',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'import-doc',
    name: 'Import documents',
    description: 'Import doclist from JSON file(s)',
    template: 'bench --site {site} import-doc {path}',
    category: 'doctype',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'bulk-rename',
    name: 'Bulk rename documents',
    description: 'Rename multiple records via CSV',
    template: 'bench --site {site} bulk-rename {doctype} {path}',
    category: 'doctype',
    destructive: true,
    requiresSite: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // BUILD — Asset compilation and serving
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'build',
    name: 'Build assets',
    description: 'Compile JS and CSS source files',
    template: 'bench build',
    category: 'build',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'watch-assets',
    name: 'Watch assets',
    description: 'Watch and auto-rebuild assets on change',
    template: 'bench watch',
    category: 'build',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'serve',
    name: 'Start dev server',
    description: 'Start the development web server',
    template: 'bench --site {site} serve --port {port}',
    category: 'build',
    destructive: false,
    requiresSite: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TEST — Running tests
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'run-tests',
    name: 'Run tests',
    description: 'Run tests for an app or module',
    template: 'bench --site {site} run-tests --app {app}',
    category: 'test',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'run-parallel-tests',
    name: 'Run parallel tests',
    description: 'Run tests in parallel across multiple processes',
    template: 'bench --site {site} run-parallel-tests --app {app}',
    category: 'test',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'run-ui-tests',
    name: 'Run UI tests',
    description: 'Run Cypress UI tests for an app',
    template: 'bench --site {site} run-ui-tests {app}',
    category: 'test',
    destructive: false,
    requiresSite: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SCHEDULER — Background jobs and scheduling
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'scheduler-status',
    name: 'Scheduler status',
    description: 'Check the scheduler status for a site',
    template: 'bench --site {site} scheduler status',
    category: 'scheduler',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'scheduler-enable',
    name: 'Enable scheduler',
    description: 'Enable the scheduler for a site',
    template: 'bench --site {site} scheduler enable',
    category: 'scheduler',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'scheduler-disable',
    name: 'Disable scheduler',
    description: 'Disable the scheduler for a site',
    template: 'bench --site {site} scheduler disable',
    category: 'scheduler',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'scheduler-pause',
    name: 'Pause scheduler',
    description: 'Pause the scheduler',
    template: 'bench --site {site} scheduler pause',
    category: 'scheduler',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'scheduler-resume',
    name: 'Resume scheduler',
    description: 'Resume the scheduler',
    template: 'bench --site {site} scheduler resume',
    category: 'scheduler',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'set-maintenance-mode',
    name: 'Set maintenance mode',
    description: 'Enable or disable maintenance mode',
    template: 'bench --site {site} set-maintenance-mode {state}',
    category: 'scheduler',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'doctor',
    name: 'Doctor check',
    description: 'Check the health of the scheduler',
    template: 'bench --site {site} doctor',
    category: 'scheduler',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'show-pending-jobs',
    name: 'Show pending jobs',
    description: 'List all pending background jobs',
    template: 'bench --site {site} show-pending-jobs',
    category: 'scheduler',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'purge-jobs',
    name: 'Purge jobs',
    description: 'Purge pending background jobs from a queue',
    template: 'bench --site {site} purge-jobs',
    category: 'scheduler',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'trigger-scheduler-event',
    name: 'Trigger scheduler event',
    description: 'Manually trigger a scheduler event',
    template: 'bench --site {site} trigger-scheduler-event {event}',
    category: 'scheduler',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'worker',
    name: 'Start worker',
    description: 'Start a background worker process',
    template: 'bench worker --queue {queue}',
    category: 'scheduler',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'worker-pool',
    name: 'Start worker pool',
    description: 'Start a pool of background workers',
    template: 'bench worker-pool --queue {queue} --num-workers {count}',
    category: 'scheduler',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'schedule',
    name: 'Start scheduler process',
    description: 'Start the main scheduler process',
    template: 'bench schedule',
    category: 'scheduler',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'ready-for-migration',
    name: 'Ready for migration?',
    description: 'Check if the site is ready for migration',
    template: 'bench --site {site} ready-for-migration',
    category: 'scheduler',
    destructive: false,
    requiresSite: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TRANSLATION
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'download-translations',
    name: 'Download translations',
    description: 'Download latest translations from translate.frappe.io',
    template: 'bench download-translations',
    category: 'translation',
    destructive: false,
    requiresSite: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UPDATE — Pulling, patching, upgrading
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'update',
    name: 'Update bench & apps',
    description: 'Pull updates, run patches, build assets, and restart',
    template: 'bench update',
    category: 'update',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'update-pull',
    name: 'Pull updates only',
    description: 'Pull latest changes without patching or building',
    template: 'bench update --pull',
    category: 'update',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'retry-upgrade',
    name: 'Retry upgrade',
    description: 'Retry a failed bench upgrade',
    template: 'bench retry-upgrade',
    category: 'update',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'switch-to-branch',
    name: 'Switch app branch',
    description: 'Switch one or more apps to a specific branch',
    template: 'bench switch-to-branch {branch} {apps}',
    category: 'update',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'switch-to-develop',
    name: 'Switch all apps to develop',
    description: 'Switch all apps to the develop branch',
    template: 'bench switch-to-develop',
    category: 'update',
    destructive: true,
    requiresSite: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // SETUP — Bench infrastructure setup
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'setup-nginx',
    name: 'Setup nginx',
    description: 'Generate and configure nginx config',
    template: 'bench setup nginx',
    category: 'setup',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'setup-reload-nginx',
    name: 'Reload nginx',
    description: 'Reload the nginx configuration',
    template: 'bench setup reload-nginx',
    category: 'setup',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'setup-supervisor',
    name: 'Setup supervisor',
    description: 'Generate supervisor configuration',
    template: 'bench setup supervisor',
    category: 'setup',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'setup-production',
    name: 'Setup production',
    description: 'Configure the bench for production (nginx + supervisor)',
    template: 'bench setup production {user}',
    category: 'setup',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'setup-backups',
    name: 'Setup backups',
    description: 'Configure automatic backups via cron',
    template: 'bench setup backups',
    category: 'setup',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'setup-env',
    name: 'Setup environment',
    description: 'Recreate the bench virtual environment',
    template: 'bench setup env',
    category: 'setup',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'setup-procfile',
    name: 'Setup Procfile',
    description: 'Generate a Procfile for the bench',
    template: 'bench setup procfile',
    category: 'setup',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'setup-socketio',
    name: 'Setup SocketIO',
    description: 'Configure SocketIO for real-time communication',
    template: 'bench setup socketio',
    category: 'setup',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'setup-redis',
    name: 'Setup Redis',
    description: 'Generate Redis configuration',
    template: 'bench setup redis',
    category: 'setup',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'setup-requirements',
    name: 'Setup requirements',
    description: 'Install Python and Node.js dependencies',
    template: 'bench setup requirements',
    category: 'setup',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'setup-lets-encrypt',
    name: 'Setup Let\'s Encrypt SSL',
    description: 'Obtain and configure SSL certificates',
    template: 'bench setup lets-encrypt {site}',
    category: 'setup',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'setup-wildcard-ssl',
    name: 'Setup wildcard SSL',
    description: 'Obtain a wildcard SSL certificate',
    template: 'bench setup wildcard-ssl {domain}',
    category: 'setup',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'setup-firewall',
    name: 'Setup firewall',
    description: 'Configure the firewall (UFW)',
    template: 'bench setup firewall',
    category: 'setup',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'setup-fail2ban',
    name: 'Setup fail2ban',
    description: 'Configure fail2ban for the bench',
    template: 'bench setup fail2ban',
    category: 'setup',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'setup-manager',
    name: 'Setup bench manager',
    description: 'Set up Frappe Bench Manager dashboard',
    template: 'bench setup manager',
    category: 'setup',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'setup-add-domain',
    name: 'Add domain to site',
    description: 'Add a custom domain to a site',
    template: 'bench setup add-domain {domain} --site {site}',
    category: 'setup',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'setup-remove-domain',
    name: 'Remove domain from site',
    description: 'Remove a custom domain from a site',
    template: 'bench setup remove-domain {domain} --site {site}',
    category: 'setup',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'setup-sudoers',
    name: 'Setup sudoers',
    description: 'Add a user to the sudoers for bench management',
    template: 'bench setup sudoers {user}',
    category: 'setup',
    destructive: true,
    requiresSite: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // INSTALL — Install system dependencies
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'install-prerequisites',
    name: 'Install prerequisites',
    description: 'Install all Frappe prerequisites (system packages)',
    template: 'bench install-prerequisites',
    category: 'install',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'install-mariadb',
    name: 'Install MariaDB',
    description: 'Install and configure MariaDB',
    template: 'bench install mariadb',
    category: 'install',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'install-nodejs',
    name: 'Install Node.js',
    description: 'Install Node.js for bench asset compilation',
    template: 'bench install nodejs',
    category: 'install',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'install-nginx',
    name: 'Install nginx',
    description: 'Install the nginx web server',
    template: 'bench install nginx',
    category: 'install',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'install-supervisor',
    name: 'Install supervisor',
    description: 'Install the supervisor process manager',
    template: 'bench install supervisor',
    category: 'install',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'install-fail2ban',
    name: 'Install fail2ban',
    description: 'Install and configure fail2ban',
    template: 'bench install fail2ban',
    category: 'install',
    destructive: true,
    requiresSite: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // NETWORK — Network & URL configuration
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'set-nginx-port',
    name: 'Set nginx port',
    description: 'Set the nginx port for a site',
    template: 'bench set-nginx-port {site} {port}',
    category: 'network',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'set-url-root',
    name: 'Set URL root',
    description: 'Set the URL root for a site',
    template: 'bench set-url-root {site} {url-root}',
    category: 'network',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'set-ssl-certificate',
    name: 'Set SSL certificate',
    description: 'Set the SSL certificate for a site',
    template: 'bench set-ssl-certificate {site} {ssl-certificate-path}',
    category: 'network',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'set-ssl-key',
    name: 'Set SSL key',
    description: 'Set the SSL certificate key for a site',
    template: 'bench set-ssl-certificate-key {site} {ssl-certificate-key-path}',
    category: 'network',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'set-mariadb-host',
    name: 'Set MariaDB host',
    description: 'Set the MariaDB database host',
    template: 'bench set-mariadb-host {host}',
    category: 'network',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'set-redis-cache-host',
    name: 'Set Redis cache host',
    description: 'Set the Redis cache host',
    template: 'bench set-redis-cache-host {host}',
    category: 'network',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'set-redis-queue-host',
    name: 'Set Redis queue host',
    description: 'Set the Redis queue host',
    template: 'bench set-redis-queue-host {host}',
    category: 'network',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'set-redis-socketio-host',
    name: 'Set Redis SocketIO host',
    description: 'Set the Redis SocketIO host',
    template: 'bench set-redis-socketio-host {host}',
    category: 'network',
    destructive: true,
    requiresSite: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PRODUCTION — Production management
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'disable-production',
    name: 'Disable production mode',
    description: 'Switch from production back to development mode',
    template: 'bench disable-production',
    category: 'production',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'renew-lets-encrypt',
    name: 'Renew Let\'s Encrypt',
    description: 'Renew all Let\'s Encrypt SSL certificates',
    template: 'bench renew-lets-encrypt',
    category: 'production',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'setup-ssh-port',
    name: 'Set SSH port',
    description: 'Change the SSH port for the server',
    template: 'bench setup ssh-port {port}',
    category: 'production',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'setup-role',
    name: 'Setup server role',
    description: 'Configure this bench as a specific server role',
    template: 'bench setup role {role}',
    category: 'production',
    destructive: true,
    requiresSite: false,
  },
  {
    id: 'setup-systemd',
    name: 'Setup systemd',
    description: 'Generate systemd service configurations',
    template: 'bench setup systemd --user {user}',
    category: 'production',
    destructive: false,
    requiresSite: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UTILITY — General utilities
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'clear-cache',
    name: 'Clear cache',
    description: 'Clear Frappe cache (Redis, doctype cache, defaults)',
    template: 'bench --site {site} clear-cache',
    category: 'utility',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'clear-website-cache',
    name: 'Clear website cache',
    description: 'Clear the website cache',
    template: 'bench --site {site} clear-website-cache',
    category: 'utility',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'rebuild-global-search',
    name: 'Rebuild global search',
    description: 'Rebuild the global search index',
    template: 'bench --site {site} rebuild-global-search',
    category: 'utility',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'build-search-index',
    name: 'Build search index',
    description: 'Build the website search index',
    template: 'bench --site {site} build-search-index',
    category: 'utility',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'restart',
    name: 'Restart bench',
    description: 'Restart all bench processes (supervisor/systemd)',
    template: 'bench restart',
    category: 'utility',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'start',
    name: 'Start bench',
    description: 'Start bench processes in development mode',
    template: 'bench start',
    category: 'utility',
    destructive: false,
    requiresSite: false,
  },
  {
    id: 'version',
    name: 'Check versions',
    description: 'Show Frappe framework and app versions',
    template: 'bench --site {site} get-version',
    category: 'utility',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'execute',
    name: 'Execute code',
    description: 'Execute a Python function on the site',
    template: 'bench --site {site} execute {method}',
    category: 'utility',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'request',
    name: 'Run HTTP request',
    description: 'Run an HTTP request as an admin',
    template: 'bench --site {site} request --path {path}',
    category: 'utility',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'jupyter',
    name: 'Start Jupyter notebook',
    description: 'Start an interactive Jupyter notebook for the site',
    template: 'bench --site {site} jupyter',
    category: 'utility',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'destroy-all-sessions',
    name: 'Destroy all sessions',
    description: 'Log out all active user sessions',
    template: 'bench --site {site} destroy-all-sessions',
    category: 'utility',
    destructive: true,
    requiresSite: true,
  },
  {
    id: 'publish-realtime',
    name: 'Publish realtime event',
    description: 'Publish a realtime event to connected clients',
    template: 'bench --site {site} publish-realtime {event} --message {message}',
    category: 'utility',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'start-recording',
    name: 'Start recording',
    description: 'Start the Frappe Recorder to trace requests',
    template: 'bench --site {site} start-recording',
    category: 'utility',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'stop-recording',
    name: 'Stop recording',
    description: 'Stop the Frappe Recorder',
    template: 'bench --site {site} stop-recording',
    category: 'utility',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'ngrok',
    name: 'Start ngrok tunnel',
    description: 'Expose the site via an ngrok tunnel',
    template: 'bench --site {site} ngrok',
    category: 'utility',
    destructive: false,
    requiresSite: true,
  },
  {
    id: 'sync-desktop-icons',
    name: 'Sync desktop icons',
    description: 'Synchronize desktop icons from app directories',
    template: 'bench --site {site} sync-desktop-icons',
    category: 'utility',
    destructive: false,
    requiresSite: true,
  },
];

/** Get a bench command by its ID. */
export function getCommandById(id: string): BenchCommand | undefined {
  return BENCH_COMMANDS.find(c => c.id === id);
}

/** Get all commands in a category. */
export function getCommandsByCategory(category: BenchCommandCategory): BenchCommand[] {
  return BENCH_COMMANDS.filter(c => c.category === category);
}

/** Resolve a command template with the given values. */
export function resolveCommand(
  command: BenchCommand,
  values: Record<string, string>
): string {
  let resolved = command.template;
  for (const [key, value] of Object.entries(values)) {
    resolved = resolved.replaceAll(`{${key}}`, value);
  }
  return resolved;
}
