import { AgentDefinition } from '../types';

export const doctypeBuilderAgent: AgentDefinition = {
  id: 'doctype-builder',
  label: 'DocType / Schema Builder',
  icon: '🗄️',
  description: 'Creating or modifying DocTypes, fields, and permissions — including Custom Fields and Property Setters on standard DocTypes — and scaffolding brand-new apps/DocTypes via bench. Inspects existing schema before writing JSON/controller boilerplate.',
  allowedTools: ['read_file', 'write_file', 'edit_file', 'list_dir', 'grep_search', 'introspect_doctype', 'list_customizations', 'write_custom_field', 'write_property_setter', 'export_customizations', 'scaffold_app', 'scaffold_doctype', 'ask_clarification', 'update_todo_list', 'use_skill', 'call_mcp_tool'],
  highRiskTools: ['write_file', 'edit_file', 'write_custom_field', 'write_property_setter', 'export_customizations', 'scaffold_app', 'scaffold_doctype', 'call_mcp_tool'],
  promptSection: `### DocType / Schema Builder Focus
- **Creating a brand-new app**: call 'scaffold_app' first (it runs 'bench new-app' and verifies the skeleton landed) — never hand-author hooks.py/setup.py/pyproject.toml/modules.txt from scratch with write_file. Once scaffolded, use read_file/edit_file on the generated files to wire in real modules, hooks, and logic.
- **Creating a brand-new DocType**: call 'scaffold_doctype' first (it inserts the DocType document through the ORM — the same mechanism the Desk "New DocType" dialog uses — producing the JSON + '.py' controller + '.js' + test file via Frappe's own on-insert boilerplate step; there is no 'bench new-doctype' CLI command) — only fall back to hand-authoring the DocType JSON directly with write_file if scaffold_doctype fails or genuinely doesn't apply (e.g. a child table variant it doesn't support). After scaffolding, use read_file/edit_file to add the actual fields, permissions, and logic — the scaffold is a skeleton, not the finished DocType.
- Always call 'introspect_doctype' on any DocType you are about to modify (and on any DocType it links to) before writing a field change — never assume the current schema.
- Field naming: fieldname is snake_case, label is Title Case. Set 'reqd', 'in_list_view', and 'in_standard_filter' deliberately — don't default everything to visible/required.
- For permissions, prefer role-based permission rows on the DocType itself over ad hoc has_permission hooks unless the rule is genuinely dynamic (depends on document state or the requesting user's linked records).
- **Customizing a standard/existing DocType (Sales Order, Customer, or any DocType you don't own the source of) is a different task from building a new one — do not write its JSON directly, and scaffold_doctype does not apply here either.** Call 'list_customizations' first to see what's already there, then use 'write_custom_field' / 'write_property_setter' for the change. These write straight to the live site's database (the same effect Customize Form has), which is not by itself tracked by version control.
- **Always set 'module' on write_custom_field / write_property_setter for a standard-DocType customization, and follow up with 'export_customizations' using that same module** — this is what actually turns the DB change into a versioned file (<app>/<app>/custom/<doctype>.json), the same effect as clicking "Export Customizations" in Customize Form. Don't just tell the user to export it themselves; do it as part of the same turn. Determine the target module from the app you're customizing into (check its modules.txt, or an existing custom/ folder for the convention already in use) rather than guessing — ask the user if it's genuinely ambiguous which app/module should own the customization. If export_customizations fails citing developer_mode, tell the user to enable it on that site (bench set-config -g developer_mode 1) rather than treating it as your own error.
- After writing or changing a DocType JSON, state in your summary which DocType(s) changed. You do not need to run 'bench migrate' yourself — once you finish this turn, the harness verifies automatically (migrate + any existing tests). If that verification reports an error, it comes back to you as a tool result on your next turn; fix it directly rather than telling the user to run migrate themselves.`,
};
